fix: override fetch search params entries
wix-incubator/netmock-js pull request #15
Opened 2022-11-09 13:07 UTC by AmitShwarts

Hey,

we encountered with the error:
this change fixed it when i tried locally.
```
 {
      error: TypeError: object is not iterable (cannot read property Symbol(Symbol.iterator))
          at Function.fromEntries (<anonymous>)
          at /Users/amitshw/github/wix-one-app-portal-platform/node_modules/netmock-js/lib/overrideFetch.js:41:34
          at Generator.next (<anonymous>)
          at /Users/amitshw/github/wix-one-app-portal-platform/node_modules/netmock-js/lib/overrideFetch.js:8:71
          at new Promise (<anonymous>)
          at new TrackedPromise (/Users/amitshw/github/wix-one-app-portal-platform/node_modules/@wix/amino/dist/src/jest-setup.js:140:13)
          at Object.<anonymous>.__awaiter (/Users/amitshw/github/wix-one-app-portal-platform/node_modules/netmock-js/lib/overrideFetch.js:4:12)
          at fetch (/Users/amitshw/github/wix-one-app-portal-platform/node_modules/netmock-js/lib/overrideFetch.js:22:37)
          at func (/Users/amitshw/github/wix-one-app-portal-platform/node_modules/wix-one-app-engine/src/engine/WixFetch/WixFetch.ts:153:46)
          at InFlightMap.launch (/Users/amitshw/github/wix-one-app-portal-platform/node_modules/wix-one-app-engine/src/engine/WixFetch/inFlightMap.ts:37:5) {
        metadata: {
          url: 'https://wix-life.com/_functions/v1/search',
          requestParams: [Object],
          retryIndex: 2
        }
      }
    }
```

2022-11-13 06:38 UTC, doronpr requested changes

2022-11-13 06:38 UTC, doronpr commented on src/overrideFetch.ts
> +      const query = Object.fromEntries(new URL(url).searchParams.entries());
@AmitShwarts thanks for the PR!
According to what I see, this makes no difference in the tests we have (see the code I used below to verify).
Can you add a failing test that is fixed by this change?

```
      const query = Object.fromEntries(new URL(url).searchParams.entries());
      const query2 = Object.fromEntries(new URL(url).searchParams);
      if (!require('lodash/isEqual')(query, query2)) {
        console.log(JSON.stringify(query)) // <-- this won't print anything
      }
```

2022-11-13 17:55 UTC, doronpr commented
@AmitShwarts I figured out the problem - `react-native-url-polyfill`  it has a different implementation for URLSearchParams 🤦🏻 
Are you able to remove it from your project?
Do you know why it's there?
It also comes from `@wix/bookings-mobile-owner`  and needs to be removed.
See test commit - https://github.com/wix-private/wix-one-app-portal-platform/pull/448/commits/1d98dd380de574b061d8df23f0bba6f6ebaa82a2

2022-11-14 06:44 UTC, doronpr commented
> react-native-url-polyfill

@AmitShwarts Another option is to simply add `jest.mock('react-native-url-polyfill');` to your jest-setup.
But I'd still recommend understanding why you need this lib

2022-11-15 09:01 UTC, AmitShwarts commented
> > react-native-url-polyfill
> 
> @AmitShwarts Another option is to simply add `jest.mock('react-native-url-polyfill');` to your jest-setup. But I'd still recommend understanding why you need this lib

Thanks @doronpr !
we will mock it until we'll be able to remove this lib.

2022-12-20 20:30 UTC, closed without merging